# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

warnings_are_errors: false

after_success: "sbt coveralls"

notifications:
  email:
    recipients:
      - luz.pascal96@gmail.comm
