app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(sim = "click")
app$snapshot()
app$setInputs(Tmax = 11)
app$setInputs(Tmax = 12)
app$setInputs(Tmax = 13)
app$setInputs(Tmax = 14)
app$setInputs(Tmax = 15)
app$snapshot()
app$setInputs(graph = "click")
app$snapshot()
app$setInputs(past = "click")
app$setInputs(length_past = 2)
app$setInputs(length_past = 3)
app$setInputs(submit_length_past = "click")
app$setInputs(past_obs_1 = "Not_seen")
app$setInputs(submit_couple_1 = "click")
app$setInputs(past_obs_2 = "Not_seen")
app$setInputs(submit_couple_2 = "click")
app$setInputs(past_obs_3 = "Not_seen")
app$setInputs(submit_couple_3 = "click")
app$setInputs(next_policy = "click")
app$snapshot()
