app <- ShinyDriver$new("../")
app$snapshotInit("test_past")

app$setInputs(past = "click")
app$setInputs(length_past = 2)
app$setInputs(length_past = 3)
app$setInputs(submit_length_past = "click")
app$setInputs(past_init_b = character(0))
app$setInputs(past_init_b = -1)
app$setInputs(submit_couple_1 = "click")
app$snapshot()
app$setInputs(past_init_b = 1)
app$setInputs(past_obs_1 = "Not_seen")
app$setInputs(submit_couple_1 = "click")
app$setInputs(past_obs_2 = "Not_seen")
app$setInputs(past_action_2 = "Survey")
app$setInputs(submit_couple_2 = "click")
app$setInputs(past_action_3 = "Stop")
app$setInputs(submit_couple_3 = "click")
app$setInputs(next_policy = "click")
app$snapshot()
app$setInputs(past_obs_3 = "Not_seen")
app$setInputs(submit_couple_3 = "click")
app$setInputs(next_policy = "click")
app$snapshot()
