app <- ShinyDriver$new("../")
app$snapshotInit("test_simulation")

app$setInputs(sim = "click")
app$setInputs(b = 0)
app$snapshot()
app$setInputs(b = character(0))
app$setInputs(b = -1)
app$snapshot()
app$setInputs(b = 0)
app$setInputs(Tmax = character(0))
app$setInputs(Tmax = -1)
app$snapshot()
app$setInputs(Tmax = 1)
app$setInputs(Tmax = 10)
app$snapshot()
