app <- ShinyDriver$new("../")
app$snapshotInit("test_graph")

app$setInputs(graph = "click")
app$snapshot()
app$setInputs(p0 = -1)
app$snapshot()
app$setInputs(p0 = 0.9)
app$setInputs(pm = character(0))
app$setInputs(pm = -1)
app$snapshot()
app$setInputs(pm = character(0))
app$setInputs(pm = 0.94184)
app$setInputs(d0 = -1)
app$snapshot()
app$setInputs(d0 = 0.01)
app$setInputs(d = -1)
app$snapshot()
app$setInputs(d = 0.78193)
app$setInputs(V = -1)
app$snapshot()
app$setInputs(V = 175.133)
app$setInputs(Cm = -1)
app$snapshot()
app$setInputs(Cm = 18.784)
app$setInputs(Cs = -1)
app$snapshot()
app$setInputs(Cs = 10.84)
app$setInputs(disc = -1)
app$snapshot()
app$setInputs(disc = 0.95)
