app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(sim = "click")
app$setInputs(b = 0)
app$snapshot()
app$setInputs(graph = "click")
app$snapshot()
app$setInputs(past = "click")
app$setInputs(submit_length_past = "click")
app$setInputs(past_obs_1 = "Not_seen")
app$setInputs(submit_couple_1 = "click")
app$setInputs(next_policy = "click")
app$snapshot()
