app <- ShinyDriver$new("../")
app$snapshotInit("testing values and reactivity")

app$snapshot()
app$setInputs(case_study = "Expensive management")
app$snapshot()
app$setInputs(reload = "click")
app$snapshot()
app$setInputs(case_study = "Detection in management")
app$setInputs(reload = "click")
app$snapshot()
app$setInputs(Tsim = 11)
app$setInputs(Tsim = 12)
app$snapshot()
app$setInputs(Tmanage = 3)
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
app$snapshot()
